### ISSUE TITLE
Some small improvements suggestions

### ISSUE THREAD

**Issue by LeonorLunatech** [input-output-hk/mantis-docs#32]
Going through `https://docs.mantisclient.io/ ` I noticed the following 3 points:

1) In the "Client quickstart" section, in the following text it's said to `choose your OS` but in this case that is not needed (and can generate confusion)
<img width="467" alt="Screenshot 2021-01-15 at 14 12 22" src="https://user-images.githubusercontent.com/20278579/104731633-4c9ddb00-573c-11eb-96a1-d792687f9f5e.png">

__________________________________________________________________________________________
2) In the "Why use Mantis" section, the following paragraph is a bit confusing and does not seem aligned with the section where it is inserted
<img width="657" alt="Screenshot 2021-01-15 at 15 15 07" src="https://user-images.githubusercontent.com/20278579/104737884-1e70c900-5745-11eb-8b14-f76846ae9045.png">

___________________________________________________________________________________________
3) In the "How to Join the Sagano testnet" section it says "To learn more, see here." but it does not point anywhere
<img width="709" alt="Screenshot 2021-01-15 at 15 24 10" src="https://user-images.githubusercontent.com/20278579/104738797-44e33400-5746-11eb-9180-f3ddfcfda60b.png">

**Comment by NeilBurgess42** [comment]
Thanks Leonor.
I think the current version of the documents address all these issues.

**Comment by drospa** [comment]
Closing it as per @NeilBurgess42
